config/routes.rb
FiveMinute::Application.routes.draw do
  get 'posts/hello' => 'posts#hello'
  resources :posts 
  resources :sudokus
  resources :sudoku_topics

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/sudoku.rb
class Sudoku < ActiveRecord::Base
	validates :field11, presence: true, inclusion: 1..9
	validates :field12, presence: true, inclusion: 1..9
	validates :field13, presence: true, inclusion: 1..9
	validates :field21, presence: true, inclusion: 1..9
	validates :field22, presence: true, inclusion: 1..9
	validates :field23, presence: true, inclusion: 1..9
	validates :field31, presence: true, inclusion: 1..9
	validates :field32, presence: true, inclusion: 1..9
	validates :field33, presence: true, inclusion: 1..9
end

app/models/sudoku_column.rb
class SudokuColumn < ActiveRecord::Base
	belongs_to :sudoku_row
end

app/models/sudoku_row.rb
class SudokuRow < ActiveRecord::Base
	belongs_to :sudoku_topic
	has_many :sudoku_columns, :dependent => :destroy
	  accepts_nested_attributes_for :sudoku_columns
end

app/models/sudoku_topic.rb
class SudokuTopic < ActiveRecord::Base
has_many :sudoku_rows, :dependent => :destroy
  accepts_nested_attributes_for :sudoku_rows
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new
    @sudoku_topic=SudokuTopic.new
    @sudoku_topic.topic="sss"
    @sudoku_topic.save
    SudokuRow.create(value: "1",sudoku_topic: @sudoku_topic)

    @test="s"

   #  @sudoku_row=SudokuRow.new
   #   @sudoku_column=SudokuColumn.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])
    mystring="1,1"
    @post.title=params[mystring]



for i in 1..9
  for i2 in 1..9


  end
end




    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  def hello
    @t = Time.now
  end
end

app/controllers/sudokus_controller.rb
class SudokusController < ApplicationController
  # GET /sudokus
  # GET /sudokus.json
  def index
    @sudokus = SudokuTopic.all


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sudokus }
    end
  end

  # GET /sudokus/1
  # GET /sudokus/1.json
  def show
    @sudoku = Sudoku.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sudoku }
    end
  end

  # GET /sudokus/new
  # GET /sudokus/new.json
  def new
    @sudoku = SudokuTopic.new


  9.times do
    row = @sudoku.sudoku_rows.build
    9.times { row.sudoku_columns.build }
  end


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sudoku }
    end
  end

  # GET /sudokus/1/edit
  def edit
    @sudoku = SudokuTopic.includes({:sudoku_rows=>:sudoku_columns}).find(params[:id])
    
    #can also use .find but need to call find before include

    #topics=[t1,t2,t3]
    #t.sudoku_rows   #=> [r_1_1,..,r_1_9]
    #r_1_1.sudoku_columns #=>[ c_1_1_1_,..,c_1_1_1_9]


    #include({:sudoku_rows=>:sudoku_columns}) 1..*
    #include([:sudoku_rows,:sudoku_columns]) *..*
  end

  # POST /sudokus
  # POST /sudokus.json
def create
    @get_sudoku_topic = SudokuTopic.new(params[:sudoku_topic])
    @get_sudoku_topic.save

     # for i in 1..9
     #    @sudoku_row=SudokuRow.new
     #    @sudoku_row.value=0   # must no value (wrong design)
     #    @sudoku_row.sudoku_topic=@get_sudoku_topic
     #    @sudoku_row.save
     #   for i2 in 1..9


     #    sudoku_column=SudokuColumn.new
     #    sudoku_column.value=params[i.to_s+","+i2.to_s] 
     #    sudoku_column.sudoku_row=@sudoku_row
     #    sudoku_column.save
     #   #SudokuRow.create(value: i.to_s+","+i2.to_s ,sudoku_topic: @get_sudoku_topic)
     #   end
     # end

    #params[:sudoku_topic][:sudoku_rows].each do |row|
     # sudoku_row = @get_sudoku_topic.sudoku_rows.build
      #row[:sudoku_columns].each do |column|
      #  sudoku_row.sudoku_columns.build(value: column[:value])
     # end
    #end  
    #@get_sudoku_topic.save



  end


  

  # PUT /sudokus/1
  # PUT /sudokus/1.json
  def update
    #@sudoku = Sudoku.find(params[:id])
   @get_sudoku_topic = SudokuTopic.new(params[:sudoku_topic])
 #  @get_sudoku_topic.topic="test update by code"
   @get_sudoku_topic.save


    respond_to do |format|
      if @sudoku.update_attributes(params[:sudoku_topic])
        format.html { redirect_to @sudoku, notice: 'Sudoku was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sudoku.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sudokus/1
  # DELETE /sudokus/1.json
  def destroy
    @sudoku = SudokuTopic.find(params[:id])
    @sudoku.destroy

    respond_to do |format|
      format.html { redirect_to sudokus_url }
      format.json { head :no_content }
    end
  end

  def hello
  	@t = "Hello Test"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FiveMinute</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :published %><br />
    <%= f.check_box :published %>
  </div>

<%for i in 1..9%>
  <%for i2 in 1..9%>

              <%# mystring =i.to_s+","+i2.to_s %>
             <%=text_field_tag (i.to_s+","+i2.to_s) %>
           
<%
    end
 end
%>


<% @sudoku_collection.all.each do |post| %>
  puts "Post:            " + post.title
  puts "Written by:      " + post.author.name
  puts "Last comment on: " + post.comments.first.created_on

  <%
end
%>
  

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/hello.html.erb
<h1>Hello post</h1>
<%= @t %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th>Published</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.title %></td>
    <td><%= post.body %></td>
    <td><%= post.published %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>



<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Body:</b>
  <%= @post.body %>
</p>

<p>
  <b>Published:</b>
  <%= @post.published %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/posts/test.html.erb
<h1>test<h1>
<table>
<tr>
	<td>test</td>
		<td>test2</td>

</tr>

</table>

app/views/sudokus/_column_fields.html.erb
<p>
  <%= f.label :value, "Value" %>
  <%= f.text_field :value %>

</p>

app/views/sudokus/_form.html.erb
<%= form_for(@sudoku, url: sudokus_path) do |f| %>
  <% if @sudoku.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sudoku.errors.count, "error") %> prohibited this sudoku from being saved:</h2>

      <ul>
      <% @sudoku.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <%= f.text_field :topic %>
   <br>

<table>
<%# @sudoku.sudoku_rows.each do |row| %>
  <%#= f.fields_for(row) do |r| %>
  <tr>
    <%# row.sudoku_columns.each do |column| %>
    
      <%#= r.fields_for(column) do |c| %>
        <%#= c.text_field(:value) %>
      <%# end %>
    <%# end %>
  </tr>
  <%# end %>
<%# end%> 
</table>
<%#for i in 1..9%>
  <%#for i2 in 1..9%>

           
             <%#=text_field_tag (i.to_s+","+i2.to_s),'12' %>
           
<%#
    end
 end
%>


<% @sudoku.sudoku_rows.each do |post| %>

  <% post.sudoku_columns.each do |post2| %>
       <%#=text_field_tag (i.to_s+","+i2.to_s),post2.value%>
    <%
  end
end
%>





  <%= f.fields_for :sudoku_rows do |builder| %>
    <%= render "row_fields", :f => builder %>
  <% end %>



<div class="actions">
    <%= f.submit %>
</div>
<% end %>

app/views/sudokus/_row_fields.html.erb
<%= f.fields_for :sudoku_columns do |builder| %>
  <%= render 'column_fields', :f => builder %>
<% end %>

app/views/sudokus/edit.html.erb
<h1>Editing sudoku</h1>

<%= render 'form' %>

<%= link_to 'Show', @sudoku %> |
<%= link_to 'Back', sudokus_path %>

app/views/sudokus/index.html.erb
<h1>Listing sudokus</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sudokus.each do |sudoku_topic| %>
  <tr>
      <td><%= sudoku_topic.id %></td>
    <td><%= sudoku_topic.topic %></td>
  
  </tr> 
  
  <tr>
    <td><%= link_to 'Show', sudoku_path(sudoku_topic) %></td>
    <td><%= link_to 'Edit', edit_sudoku_path(sudoku_topic) %></td>
    <td><%= link_to 'Destroy', sudoku_path(sudoku_topic), confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sudoku', new_sudoku_path %>

app/views/sudokus/new.html.erb
<h1>New sudoku</h1>

<%= render 'form' %>

<%= link_to 'Back', sudokus_path %>

app/views/sudokus/show.html.erb
<p id="notice"><%= notice %></p>

<table>
  <tr>
    <td><%= @sudoku.field11 %></td>
    <td><%= @sudoku.field12 %></td>
    <td><%= @sudoku.field13 %></td>
  </tr> 
  <tr>
    <td><%= @sudoku.field21 %></td>
    <td><%= @sudoku.field22 %></td>
    <td><%= @sudoku.field23 %></td>
  </tr> 
  <tr>
    <td><%= @sudoku.field31 %></td>
    <td><%= @sudoku.field32 %></td>
    <td><%= @sudoku.field33 %></td>
  </tr>

  <tr>
      <% @temp = [1,2,3,4,5,6,7,8,9] %>
      <% @c = [@sudoku.field11,@sudoku.field12,@sudoku.field13,@sudoku.field21,@sudoku.field22,@sudoku.field23,@sudoku.field31,@sudoku.field32,@sudoku.field33] %>
      <td colspan = "3"><%='Result : ' %> <%= @c.sort == @temp %> <td>
  </tr>
</table>


<%= link_to 'Edit', edit_sudoku_path(@sudoku) %> |
<%= link_to 'Back', sudokus_path %>